apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.appNamespace }}
  labels:
    istio.io/dataplane-mode: ambient   # ztunnel이 이 네임스페이스 트래픽을 L4 터널링
    istio.io/use-waypoint: waypoint    # L7 트래픽을 waypoint proxy로 라우팅
