apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.kafkaConnect.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.kafkaConnect.name }}
  ports:
    - port: {{ .Values.kafkaConnect.port }}
      targetPort: {{ .Values.kafkaConnect.port }}
