---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.tempo.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  tempo.yaml: |
{{ .Files.Get "files/tempo.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tempo.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.tempo.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "promotion-monitoring.chart" . }}
spec:
  replicas: {{ .Values.tempo.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tempo.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tempo.name }}
        app.kubernetes.io/name: {{ .Values.tempo.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.tempo.name }}
          image: {{ .Values.tempo.image }}
          imagePullPolicy: Always
          args: ["-config.file=/etc/tempo.yaml"]
          ports:
            - containerPort: {{ .Values.tempo.port }}
              name: http
            - containerPort: 4317
              name: grpc-otlp
          volumeMounts:
            - name: config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
          resources:
            requests:
              cpu: {{ .Values.tempo.resources.requests.cpu | quote }}
              memory: {{ .Values.tempo.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.tempo.resources.limits.cpu | quote }}
              memory: {{ .Values.tempo.resources.limits.memory | quote }}
      volumes:
        - name: config
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.tempo.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.tempo.name }}
  ports:
    - name: http
      port: {{ .Values.tempo.port }}
      targetPort: {{ .Values.tempo.port }}
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
