server:
  port: 8080
  shutdown: graceful
  tomcat:
    accept-count: 1000

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/weverse_promo?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: worldcup7!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      jdbc.batch_size: 500
      order_inserts: true
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    root: WARN

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
  instances:
    serverBClient:
      baseConfig: default

external:
  server-b:
    url: http://localhost:8081
  server-c:
    url: http://localhost:8082