server:
  port: 8081
  tomcat:
    accept-count: 1000

spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6380}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
        linger.ms: 10
        batch.size: 130000
        compression-type: zstd
        request.timeout.ms: 30000
    consumer:
      group-id: server-b-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.poll.interval.ms: 600000
        max.poll.records: 500

external:
  server-c:
    url: http://localhost:8082
  server-a:
    url: http://localhost:8080

logging:
  level:
    root: WARN

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
  instances:
    serverCClient:
      baseConfig: default
    serverAClient:
      baseConfig: default