server:
  port: 8081
  tomcat:
    accept-count: 1000

spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

external:
  server-c:
    url: http://localhost:8082
  server-a:
    url: http://localhost:8080

logging:
  level:
    root: WARN

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
  instances:
    serverCClient:
      baseConfig: default
    serverAClient:
      baseConfig: default