server:
  port: 8081
  tomcat:
    accept-count: 1000

spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

external:
  server-c:
    url: http://localhost:8082

logging:
  level:
    root: WARN