apiVersion: v1
kind: ServiceAccount
metadata:
  name: cs-bot
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: cs-bot
    app.kubernetes.io/managed-by: {{ .Release.Service }}
