spring:
  application:
    name: mcp
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  ai:
    google:
      genai:
        api-key:
        chat:
          options:
            model: gemini-3.1-flash-lite

server:
  port: 8085

observability:
  loki:
    url: http://loki:3100
  tempo:
    url: http://tempo:3200
  prometheus:
    url: http://prometheus:9090

slack:
  webhook-url:
logging:
  level:
    root: WARN
    mcp.mcp: INFO
