route:
  group_by: ['alertname', 'app']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 1m  # 1분마다 중복 알람 계속 쏨 (테스트용)
  receiver: 'aiops-agent'

receivers:
- name: 'aiops-agent'
  webhook_configs:
  - url: 'http://mcp:8085/webhook/prometheus'
    send_resolved: true
