global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 알람 규칙 파일 명시
rule_files:
  - "/etc/prometheus/alert-rules.yml"

scrape_configs:
  - job_name: 'promotion-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['server-a:8080', 'server-b:8081', 'server-c:8082']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          instance: 'redis-a'
      - targets: ['redis-b-exporter:9121']
        labels:
          instance: 'redis-b'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-a-exporter:9104']
        labels:
          instance: 'mysql-a'
      - targets: ['mysql-c-exporter:9104']
        labels:
          instance: 'mysql-c'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']