apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.kafka.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.kafka.name }}
  ports:
    - name: plaintext
      port: {{ .Values.kafka.port }}
      targetPort: {{ .Values.kafka.port }}
