apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        groupBy: ['app']
        filterByTraceID: true
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        tags:
          - key: 'service.name'
            value: 'app'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'
      tracesToProfiles:
        datasourceUid: 'pyroscope'
        tags: ['service.name']

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://pyroscope:4040

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceId":"([a-zA-Z0-9]+)"'
          name: trace_id
          url: "$${__value.raw}"

  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://alertmanager:9093
    jsonData:
      handleGrafanaManagedAlerts: false
      implementation: prometheus
